import useVariablesStore from "@/hooks/useVariablesStore";
import { exists, readTextFile, writeTextFile } from "@tauri-apps/plugin-fs";
import { BASE_DIRECTORY } from "../types";

export const VARIABLES_FILENAME = "variables";

export const generateCssVariablesTemplate = async () => {
  const cssVariableModules = import.meta.glob("/src/widgets/*/Variables.css", {
    eager: true,
    query: "raw",
    import: "default",
  }) as Record<string, string>;
  const rootStyles = import.meta.glob("/src/assets/variables.css", {
    eager: true,
    query: "raw",
    import: "default",
  }) as Record<string, string>;
  const widgetCssVariables: Record<string, string> = { root: rootStyles["/src/assets/variables.css"] };

  for (let [path, mod] of Object.entries(cssVariableModules)) {
    const widgetName = path.match(/\/src\/widgets\/(.+)\/Variables\.css$/)![1];
    if (mod && typeof mod === "string") {
      widgetCssVariables[widgetName] = mod;
    }
  }

  const mergedCssVariables: string[] = [];

  Object.entries(widgetCssVariables).forEach(([name, css]) => {
    const match = css.match(/:root\s*\{([\s\S]*?)\}/);
    if (match) {
      const content = "  " + match[1].trim();
      mergedCssVariables.push(`  /* ${name} widget variables */`);
      mergedCssVariables.push(content);
    }
  });

  const template = `
:root {
${mergedCssVariables.join("\n")}
}`;

  if (!(await exists(`${VARIABLES_FILENAME}.css`, { baseDir: BASE_DIRECTORY }))) {
    await writeTextFile(
      `${VARIABLES_FILENAME}.css`,
      `/* Custom CSS variables - uncomment and modify from variables.template.css */
${template}`,
      { baseDir: BASE_DIRECTORY },
    );
  }

  await writeTextFile(
    `${VARIABLES_FILENAME}.template.css`,
    `/* 
 * DO NOT EDIT THIS FILE - it is auto-generated on app startup
 * To customize variables, edit variables.css instead
 */
${template}`,
    { baseDir: BASE_DIRECTORY },
  );
};

export const loadCssVariables = async () => {
  const variablesPath = `${VARIABLES_FILENAME}.css`;

  const template = await readTextFile(`${VARIABLES_FILENAME}.template.css`, { baseDir: BASE_DIRECTORY });

  let css = template;
  if (await exists(variablesPath, { baseDir: BASE_DIRECTORY })) {
    const variablesContent = await readTextFile(variablesPath, { baseDir: BASE_DIRECTORY });
    useVariablesStore.getState().setVariables(variablesContent, false);
    css += "\n" + variablesContent;
  }

  const styleElement = document.createElement("style");
  styleElement.setAttribute("id", "widget-variables");
  styleElement.textContent = css;
  document.head.appendChild(styleElement);
};
